keyword = "keyword"
# To post discord/misskey, set `false`.
dryrun = true
cron = "25 0 22 * * *" # JST 07:00

# Optional
# If you don't need this, remove this section.
[discord]
token = "discord-app-token"
chid = [0] #discord-chid
bot_watching_target = "ニコニコ動画"

# Optional
# If you don't need this, remove this section.
[misskey]
server_domain = "example.com"
token = "misskey-token"
post_footer = "#新着"
