[package]
name = "niconico-watcher-rust"
version = "0.1.0"
authors = ["moko256"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"


[dependencies]
async-trait = "0.1.41"
cron = "0.6.1"
serde = "1.0.117"
log = "0.4.11"
dotenv = "0.15.0"
chrono = { version = "0.4.19", features = ["serde"]}

[dependencies.tokio]
version = "0.2.22"
default-features = false
features = [
    "fs",
    "macros",
    "rt-core",
    "sync",
    "time",
    "udp",
    "process",
    "dns",
    "io-driver",
]

[dependencies.reqwest]
version = "0.10.8"
default-features = false
features = ["rustls-tls", "json"]

[dependencies.serenity]
version = "0.9.0-rc.4"
default-features = false
features = [
    "client",
    "http",
    "gateway",
    "model",
    "rustls_backend",
]

[dev-dependencies]
lazy_static = "1.4.0"