[package]
name = "niconico-watcher-rust"
version = "0.1.0"
authors = ["moko256"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"


[dependencies]
async-trait = "0.1.48"
bytes = "1.0.1"
chrono = "0.4.19"
cron = "0.8.0"
dotenv = "0.15.0"
log = { version = "0.4.14", features = ["max_level_info"]}
once_cell = "1.7.2"
form_urlencoded = "1.0.1"
quick-xml = "0.22.0"

[dependencies.rss]
version = "1.10.0"
default-features = false

[dependencies.tokio]
version = "1.4.0"
default-features = false
features = [
    "macros",
    "rt",
    "time",
]

[dependencies.reqwest]
version = "0.11.2"
default-features = false
features = ["rustls-tls", "gzip"]

[dependencies.serenity]
version = "0.10.4"
default-features = false
features = [
    "client",
    "http",
    "gateway",
    "model",
    "rustls_backend",
]
